require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'mobileWebRtc' do

  config = use_native_modules!


  use_react_native!(:path => config["reactNativePath"])

  target 'mobileWebRtcTests' do

  
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
end

target 'mobileWebRtc-tvOS' do
  # Pods for mobileWebRtc-tvOS

  target 'mobileWebRtc-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
